name: Build Standalone with Nuitka

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    name: Build Windows Standalone
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
        
    - name: Install Playwright Browsers
      run: |
        python -m playwright install chromium



    - name: Build Standalone with Nuitka
      run: |
        python -c "import shutil; shutil.copy('main.py', 'Rox-Shooter.py')"
        python -m nuitka --standalone --windows-console-mode=disable --enable-plugin=tk-inter --include-data-files=rox-logo.png=rox-logo.png --assume-yes-for-downloads Rox-Shooter.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rox-Shooter
        path: Rox-Shooter.dist
        retention-days: 1
